### PR TITLE
Move crash properties set as `Extra` to a separate Sentry context

### LINKED ISSUE #411: Move `Extra` event values to their own context
_Originally posted by @bitsandfoxes in https://github.com/getsentry/sentry-unreal/pull/410#discussion_r1361747180_

### PR DESCRIPTION
**Pull request by tustanivsky**
Closes #411

### CODE REVIEW

File: plugin-dev/Source/Sentry/Private/Desktop/CrashReporter/SentryCrashContext.cpp [hunk 1]
```diff
@@ -33,31 +33,35 @@ void FSentryCrashContext::Apply(TSharedPtr<SentryScopeDesktop> Scope)
...
+	ContextValues.Add("App Default Locale", SessionContext.DefaultLocale);
+	ContextValues.Add("Language LCID", FString::FromInt(SessionContext.LanguageLCID));
+	ContextValues.Add("Base Dir", SessionContext.BaseDir);
+	ContextValues.Add("Is Source Distribution", SessionContext.bIsSourceDistribution ? TEXT("true") : TEXT("false"));
+	ContextValues.Add("Crash GUID", SessionContext.CrashGUIDRoot);
+	ContextValues.Add("Executable Name", SessionContext.ExecutableName);
+	ContextValues.Add("Game Name", SessionContext.GameName);
+	ContextValues.Add("Process Id", FString::FromInt(SessionContext.ProcessId));
+	ContextValues.Add("Seconds Since Start", FString::FromInt(SessionContext.SecondsSinceStart));
+	ContextValues.Add("Command Line", SessionContext.CommandLine);
```
Comment (bitsandfoxes) [inline plugin-dev/Source/Sentry/Private/Desktop/CrashReporter/SentryCrashContext.cpp:54]: NIT: I noticed that the `command line` seems to have a trailing whitespace. We could trim that.

**Review by bitsandfoxes — APPROVED** [review]

File: plugin-dev/Source/Sentry/Private/Desktop/CrashReporter/SentryCrashContext.cpp (hunk 1 above)
Comment (tustanivsky) [reply plugin-dev/Source/Sentry/Private/Desktop/CrashReporter/SentryCrashContext.cpp]: Good catch!
