### PR TITLE
Fix Sentry cURL transport can't send envelopes on Linux

### LINKED ISSUE #876: can't send message on linux.
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

install 
add a test "capture message" node on bp or cpp.
package
run

### Expected Result

works and be able to see it in the portal.
(btw it's absolutely unclear where in the portal you can see it)

### Actual Result

doesn't work. 
at best i get an error.
    Connected to xxxxxxxxxxx.ingest.de.sentry.io (ip) port 443
    ALPN: curl offers h2,http/1.1
    SSL certificate problem: unable to get local issuer certificate
    Closing connection

    [2025.04.18-04.25.56:854][ 62]LogSentrySdk: Warning: curl_easy_perform failed with code 60: SSL certificate problem: unable to get local issuer certificate

i've already have the root certs installed on my machine. unfortunately it still doesn't work. 
if this were to happen on other players clients then i can't really fix it. 

Linux nande-desk 6.8.0-58-generic getsentry/sentry#60-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 14 18:29:48 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 24.04.2 LTS
kde/x11

### Product Area

Unknown

### Link

jerobarraco.sentry.io/projects/lifedev/

### DSN

https://0a3231a8f61771671400318026bd6bbf@o4509172003635200.ingest.de.sentry.io/4509172007370832

### Version

_No response_

### PR DESCRIPTION
**Pull request by tustanivsky**
This PR addresses an issue with using the cURL transport for `sentry-native` on Linux which was preventing envelopes from being sent to Sentry. The fix involves providing a valid CA certificate path during Native SDK initialization.

Unreal Engine follows a similar approach in its Unix-specific `IHttpRequest` implementation. This also explains why things worked as expected previously when a custom transport was in place (removed in #748).

Closes #876

### CODE REVIEW

File: plugin-dev/Source/Sentry/Private/Linux/LinuxSentrySubsystem.cpp [hunk 1]
```diff
@@ -15,6 +17,32 @@ void FLinuxSentrySubsystem::ConfigureDatabasePath(sentry_options_t* Options)
...
+
+		if (FPaths::FileExists(FileName))
+		{
+			UE_LOG(LogSentrySdk, Log, TEXT("Sentry transport will use the certificate found at %s for verification."), *FileName);
+			sentry_options_set_ca_certs(Options, BundlePath);
+			return;
+		}
+	}
+
+	UE_LOG(LogSentrySdk, Warning, TEXT("Could not find CA certificates in any known location. Sentry transport may not function properly."));
```
Comment (bruno-garcia) [inline plugin-dev/Source/Sentry/Private/Linux/LinuxSentrySubsystem.cpp:43]: We could be more clear about what this means? Like "
```suggestion
	UE_LOG(LogSentrySdk, Warning, TEXT("Could not find CA certificates in any known location. Sentry transport may not function properly for handled events"));

```
? Is this the case?

**Review by bruno-garcia — APPROVED** [review]
Approving to unblock but you prob want someone else reviewing this

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:
