### PR TITLE
Fix permissions issue on Mac/Linux

### LINKED ISSUE #74: Event capturing stopped working on Mac
### Environment

Which version of Unreal?

UE 4.27, Mac OS

### Steps to Reproduce

1. Download the latest plugin version and it's dependencies using `init.sh` script
2. Launch `PlaygroundSentry` project from `sample` folder
3. Start `SentryDemo` scene

### Expected Result

Events are captured normally and displayed in the Sentry dashboard.

### Actual Result

When trying to run the demo scene in the editor it hangs infinitely.
In packaged build demo runs without issues however events aren't captured.

### PR DESCRIPTION
**Pull request by tustanivsky**
Closes #74 

#skip-changelog

### CODE REVIEW

File: scripts/download-sdks.sh [hunk 1]
```diff
@@ -30,4 +30,5 @@ for sdk in "${sdks[@]}"; do
     echo "Downloading $sdk SDK to $PWD/$sdk ..."
     rm -rf "./$sdk"
     gh run download $runId -n "$sdk-sdk" -D $sdk
+    chmod -R +x $sdk
```
Comment (vaind) [inline scripts/download-sdks.sh:33]: doing a recursive `chmod +x` may delay discovering permission issues with packaging - maybe only change what really needs changing, i.e. the crashpad handler executables?

Comment (tustanivsky) [reply scripts/download-sdks.sh]: Good point, changed that

**Review by vaind — APPROVED** [review]
