### PR TITLE
Fix crash when re-initializing Sentry

### LINKED ISSUE #592: Crash when re-initializing the sentry subsystem
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
Git-URL, 18.0 git hub release for unreal 5.3

Which version of Unreal?
Unreal 5.3.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
We only use sentry for the windows game target for now.

### Steps to Reproduce

1. Initialize the sentry subsystem with a call to InitWithSettings, Initialize or setting InitAutomatically in USentrySettings to true
2. Initialize the sentry subsystem again later when having more data by calling InitWithSettings or Initialize again without calling Deinitialize first
3. Wait for a log message to be printed by unreal

### Expected Result

The app should not crash.

### Actual Result

The app crashes

### Any logs or screenshots

The reason for the crash is that when calling Initialize multiple times the  `FSentryOutputDevice` instance in OutputDevice gets destroyed without deregistering them first from GLog (see [USentrySubsystem::ConfigureOutputDevice()](https://github.com/getsentry/sentry-unreal/blob/e68c009748a587420a9f111e2bd077bc70f75740/plugin-dev/Source/Sentry/Private/SentrySubsystem.cpp#L642) ). 

Similar problems might be in `USentrySubsystem::ConfigureOutputDeviceError()` as the old FSentryOutputDeviceError device is still in GError when it is torn down while being used at the same time as the parent for the newly created device.

### PR DESCRIPTION
**Pull request by tustanivsky**
This PR fixes the internal plugin crash when re-initializing `USentrySubsystem` without its explicit closing beforehand.

The crash was related to custom Sentry output devices that were not deregistered properly upon any subsequent initialization attempt.

Also, assertion/ensure delegates are now deregistered too whenever calling subsystem's `Close` method to avoid potential reporting of the same event multiple times if re-init occured.

Closes #592

### CODE REVIEW

File: plugin-dev/Source/Sentry/Private/SentrySubsystem.cpp [hunk 1]
```diff
@@ -154,11 +163,25 @@ void USentrySubsystem::Close()
...
+		}
+
 		GError = OutputDeviceError->GetParentDevice();
+		OutputDeviceError = nullptr;
+	}
+
+	if(OnEnsureDelegate.IsValid())
+	{
+		FCoreDelegates::OnHandleSystemEnsure.Remove(OnEnsureDelegate);
+		OnEnsureDelegate.Reset();
```
Comment (bitsandfoxes) [inline plugin-dev/Source/Sentry/Private/SentrySubsystem.cpp:184]: Should this go into the closure above as well?

Comment (tustanivsky) [reply plugin-dev/Source/Sentry/Private/SentrySubsystem.cpp:184]: No, in order to capture ensures we don't use any of our custom output devices but rather rely on the engine's `FCoreDelegates::OnHandleSystemEnsure` delegate.

**Review by bitsandfoxes — APPROVED** [review]
LGTM!
